#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

ROOT_DIR="$(dirname $0)/.."

poetry run mypy "$ROOT_DIR/updater"
poetry run black "$ROOT_DIR/updater" && git add "$ROOT_DIR/updater"

npx pretty-quick --staged
npm run validate
npm run build && git add "$ROOT_DIR/docs/build"
